name: Flask App CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # You can specify any Python version here

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt  # Install dependencies from requirements.txt

    # Step 4: Run Flask app (or you can test here)
    - name: Run Flask App
      run: |
        nohup python app.py &  # Run the Flask app in the background (useful for testing)
   
